### PR TITLE
Add Hael9

### PR DESCRIPTION
**Pull request by ThunderW0lf**
Features:
- Automatic Terminal Solver
- Bonemerang Macro
- Hyperion Autoclicker
- Ghost Block creator
- Right click spammer
- NoRotate (prevents AOTE/Hyperion from changing head rotation)
- Controls/Hotkeys can be set in controls menu

Delays and values for the different features can be set with the following commands:
- /bonedelay [time between switching bonemerangs in ms]
- /rightclickamount [# of clicks per physical right click]
- /sleepamount [time between terminal solver clicks in ms]
- /swapdelay [delay in ms]
- /norotate

To turn on terminal solvers, do "/dsm", click "Toggle Dungeon Puzzle Solvers", and turn on any of the buttons with the word "Terminal" on it.

Credit goes to Hael

### CODE REVIEW

**Comment by SkyBlockDev** [comment]
But why

**Comment by BrahR** [comment]
Kinda sus

**Comment by AzuredBlue** [comment]
great pull request I'll be looking forward to the merge

**Comment by bowser0000** [comment]
Outdated code kinda crinkey crongemas

**Pull request closed without merging**
