### PR TITLE
Features: Old Animations Warning, cooldown messages, mana messages, and secrets found

### PR DESCRIPTION
**Pull request by Sychic**
#### Old Animations Warning
Just a GUI which pops up after loading in alerting users to incompatibilities with the Old Animations Mod by SpiderFrog.
#### Cooldown and Mana messages
Toggle ability on cooldown messages and out of mana messages.
#### Secrets Found
Added total secrets found to the /dungeons command.

#### Reparty fixes
Changed message cancelling and divided the reparty process into multiple sections. Yields to other reparty commands if they exist, otherwise it'll use DSM's
~~Moved to separate pr~~
Merged back into this pr

##### Bug Fix
Werewolfs fished weren't being written to the correct config key.

### CODE REVIEW

**Comment by Sychic** [comment]
updated code to resolve conflicts

**Comment by bowser0000** [comment]
Add the toggles to DankerGui

**Review by Sychic — COMMENTED** [review]
works when compiled

**Comment by Sychic** [comment]
I'm just gonna wait until this pr is accepted before starting a new one

**Comment by Sychic** [comment]
I'm a clown...

**Pull request merged**
